# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-26 03:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg_app', '0004_remove_quote_quoter'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='userQuote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserQuote', to='login_reg_app.User'),
        ),
    ]
