# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-26 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg_app', '0006_quote_postedby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='PostedBy',
            field=models.CharField(max_length=255),
        ),
    ]
