# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-26 18:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg_app', '0007_auto_20190626_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='PostedBy',
        ),
    ]
