# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-26 19:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg_app', '0008_remove_quote_postedby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='userQuote',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='UserQuote', to='login_reg_app.User'),
            preserve_default=False,
        ),
    ]
