# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-26 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg_app', '0009_auto_20190626_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(default=0, max_length=60),
            preserve_default=False,
        ),
    ]
